### ISSUE TITLE
Subir Test de Sobre Git

### ISSUE THREAD

**Issue by MHCelso** [JoinBugs/LEARNGIT#1]
# Deben subir el cuestionario sobre git.
- Deben clonar el Repositorio en un espacio local de su pc
- Crear la carpeta con su nombre `nombre`
- Contestar la encuesta
- Hacer commit
- Finalmente hacer push.

_Esto fue un ejemplo de un **Issues**_

**Comment by MHCelso** [comment]
dejare un msg por aqui

**Comment by JoinBugs** [comment]
ok, que bien celso, esto de los issues esta chido
